apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "plex-rclone-wireguard.fullname" . }}
  labels:
    {{- include "plex-rclone-wireguard.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plex-rclone-wireguard.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "plex-rclone-wireguard.fullname" . }} 
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plex-rclone-wireguard.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plex-rclone-wireguard.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:           
        - name: health-script-init
          image: "busybox"
          command:
            - cp
          args:
            - -v
            - /in/health-script.sh
            - /out/health-script.sh
          volumeMounts:
          - name: health-data
            mountPath: /in
          - name: health
            mountPath: /out   
        - name: permission-fix
          image: busybox
          command: ['sh', '-c']
          args: ['chmod -R 655 /out']
          volumeMounts:
          - name: health
            mountPath: /out  
        - name: rclone-config
          image: "busybox"
          command:
            - cp
          args:
            - -v
            - /in/rclone.conf
            - /out/rclone.conf
          volumeMounts:
            - name: rclone-config
              mountPath: /in
            - name: rclone-data
              mountPath: /out
        - name: import-wireguard-config
          image: "busybox"
          command:
            - cp
          args:
            - -v
            - /in/wg7.conf
            - /out/wg7.conf
          volumeMounts:
            - name: wireguard-config
              mountPath: /in
            - name: wireguard-data
              mountPath: /out       
        - name: add-init-script
          image: "busybox"
          command:
            - cp
          args:
            - -v
            - /in/init.sh
            - /out/init.sh
          volumeMounts:
            - name: init-script-data
              mountPath: /in
            - name: init-script
              mountPath: /out  
        - name: permission-fix-init-script
          image: busybox
          command: ['sh', '-c']
          args: ['chmod -R 777 /out']
          volumeMounts:
          - name: init-script
            mountPath: /out                                          
      containers:
        - image: luiscajl/rclone-wireguard
          name: rclone-wireguard
          imagePullPolicy: Always
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
            limits:
              cpu: "1000m"
              memory: "1000M"  
          command:
            [
              "sh",
              "-c",
              "/tmp/init/init.sh",
            ]
          volumeMounts:
            - mountPath: /data
              name: data
              mountPropagation: Bidirectional
            - mountPath: /etc/wireguard
              name: wireguard-data
            - mountPath: /etc/rclone
              name: rclone-data    
            - mountPath: /health
              name: health                   
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /health/health-script.sh
                - liveness-rclone        
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5                                       
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port}}
              protocol: TCP
          volumeMounts:
            {{- if .Values.volumes.config.enabled }}
            - mountPath: /config
              name: plex-rclone-wireguard-config-volume
            {{- end }}                
            {{- if .Values.volumes.data.enabled }}
            - mountPath: /media
              name: data     
              mountPropagation: Bidirectional  
            {{- end }}          
            - mountPath: /health
              name: health                    
          env:
            {{- range .Values.environmentVariables }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}     
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - /health/health-script.sh
                - readiness
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /health/health-script.sh
                - liveness
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5   
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}  
      volumes: 
      {{- if .Values.volumes.data.enabled }}
        - name: data
          emptyDir: {}
      {{- end }}                
        - name: health-data
          configMap:
            name: plex-rclone-wireguard-health  
            items:
              - key: health-script.sh
                path: health-script.sh
        - name: health
          emptyDir: {} 
        - name: wireguard-data
          emptyDir: {}
        - name: rclone-data
          emptyDir: {}
        - name: init-script
          emptyDir: {}               
        - name: wireguard-config
          configMap:
            name: wireguard-config
            items:
              - key: wg7.conf
                path: wg7.conf
        - name: rclone-config
          configMap:
            name: rclone-config
            items:
              - key: rclone.conf
                path: rclone.conf  
        - name: init-script-data
          configMap:
            name: init-script-rclone-wireguard-for-plex
            items:
              - key: init.sh
                path: init.sh                         
  {{- if .Values.volumes.config.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: plex-rclone-wireguard-config-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.volumes.config.storageClass }}
        resources:
          requests:
            storage: {{ .Values.volumes.config.size }}    
  {{- end }}                