dns: 
  name: example.com
  cron: "*/1 * * * *"
  proxied: true  
replicaCount: 1
image:
  repository: oznu/cloudflare-ddns
  pullPolicy: IfNotPresent
  tag: "latest"
nameOverride: ""
fullnameOverride: ""

resources: 
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

nodeSelector: {}

affinity: {}
