paths:
  torrents: /mnt/rclone-writer 
replicaCount: 1
image:
  repository: binhex/arch-qbittorrentvpn
  pullPolicy: Always
  tag: 4.5.0-1-01       
environmentVariables:
  - name: VPN_ENABLED
    value: "no" 
  - name: VPN_PROV
    value: airvpn
  - name: VPN_CLIENT
    value: openvpn
  - name: ENABLE_PRIVOXY
    value: "no"
  - name: LAN_NETWORK 
    value: 0.0.0.0/0
  - name: NAME_SERVERS 
    value: 84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
  - name: VPN_INPUT_PORTS  
    value: 1234 
  - name: VPN_OUTPUT_PORTS  
    value: 5678 
  - name: DEBUG 
    value: true 
  - name: WEBUI_PORT 
    value: 8080
  - name: UMASK 
    value: 000
  - name: PUID 
    value: 0
  - name: PGID 
    value: 0 
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  privileged: true
  capabilities:
    add: ["NET_ADMIN", "SYS_TIME","SYS_ADMIN"]

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
