environmentVariables:
    - name: VPN_ENABLED
      value: "yes" 
    - name: VPN_PROV
      value: airvpn
    - name: VPN_CLIENT
      value: wireguard
    - name: ENABLE_PRIVOXY
      value: "yes"
    - name: LAN_NETWORK 
      value: 192.168.1.0/24
    - name: NAME_SERVERS 
      value: 84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
    - name: VPN_INPUT_PORTS  
      value: 1234 
    - name: VPN_OUTPUT_PORTS  
      value: 5678 
    - name: DEBUG 
      value: false 
    - name: WEBUI_PORT 
      value: 8080
    - name: UMASK 
      value: 000
    - name: PUID 
      value: 0
    - name: PGID 
      value: 0 

paths:
  torrents: /mnt/storagebox
replicaCount: 1

image:
  repository: binhex/arch-qbittorrentvpn
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  privileged: true
  capabilities:
    add: ["NET_ADMIN", "SYS_TIME","SYS_ADMIN"]

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
