apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plex.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plex.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 32400
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: plex-config-volume
            # - mountPath: /tmp/transcode
            #   name: plex-transcode-volume
            - mountPath: /media/4TB_1
              name: plex-media-1volume  
            - mountPath: /media/4TB_2
              name: plex-media-2volume  
            - mountPath: /media/4TB_3
              name: plex-media-3volume 
            - mountPath: /media/4TB_4
              name: plex-media-4volume
            - mountPath: /media/Externo8TB_1
              name: plex-media-5volume  
            - mountPath: /media/Externo8TB_2
              name: plex-media-6volume               
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: VERSION
              value: "docker"      
          livenessProbe:
            httpGet:
              path: /identity
              port: 32400
            initialDelaySeconds: 15  
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1  
          readinessProbe:
            httpGet:
              path: /identity
              port: 32400
            initialDelaySeconds: 15  
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1   
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: plex-config-volume
          persistentVolumeClaim:
            claimName: plex-config  
        - name: plex-media-1volume
          nfs:
           server: 10.10.120.50
           path: /media/4TB_1
        - name: plex-media-2volume
          nfs:
           server: 10.10.120.50
           path: /media/4TB_2
        - name: plex-media-3volume
          nfs:
           server: 10.10.120.50
           path: /media/4TB_3
        - name: plex-media-4volume
          nfs:
           server: 10.10.120.50
           path: /media/4TB_4
        - name: plex-media-5volume
          nfs:
           server: 10.10.120.50
           path: /media/Externo8TB_1
        - name: plex-media-6volume
          nfs:
           server: 10.10.120.50
           path: /media/Externo8TB_2
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
