kind: ConfigMap
apiVersion: v1
metadata:
  name: qbittorrent-health 
data:
  liveness.sh: |
    #!/bin/bash
    if [ "ls /data/torrenting" ]; then
      curl http://localhost:8080
      echo 0
    else
      echo "Liveness failed!" 1>&2
      exit 1
    fi
  