apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qbittorrentvpn.fullname" . }}-rclone-cache
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 400Gi