apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrentvpn.fullname" . }}
  labels:
    {{- include "qbittorrentvpn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8118
      targetPort: 8118
      protocol: TCP
      name: privoxy
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: bitrorrent-ui
    - port: 6881
      targetPort: 6881
      protocol: TCP
      name: vpn
     - port: 6881
      targetPort: 6881
      protocol: UDP
      name: vpn-udp  
  selector:
    {{- include "qbittorrentvpn.selectorLabels" . | nindent 4 }}
