apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "qbittorrentvpn.fullname" . }}
  labels:
    {{- include "qbittorrentvpn.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "qbittorrentvpn.fullname" . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "qbittorrentvpn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "qbittorrentvpn.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qbittorrentvpn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          emptyDir: {}
        - name: etc-localtime
          hostPath:
            path: /etc/localtime
        - name: scripts
          configMap:
            name: qbittorrent-scripts     
        - name: health-data
          configMap:
            name: qbittorrent-health  
            items:
              - key: liveness.sh
                path: liveness.sh
        - name: wireguard-data-airvpn
          configMap:
            name: wireguard-config-airvpn  
            items:
              - key: wg0.conf
                path: wg0.conf                
        - name: health
          emptyDir: {}      
        - name: wireguard-data
          emptyDir: {}
        - name: rclone-data
          emptyDir: {}
        - name: wireguard-config
          configMap:
            name: wireguard-config
            items:
              - key: wg2.conf
                path: wg2.conf
        - name: wireguard-config-2
          configMap:
            name: wireguard-config
            items:
              - key: wg-airvpn.conf
                path: wg-airvpn.conf                
        - name: rclone-config
          configMap:
            name: rclone-config
            items:
              - key: rclone.conf
                path: rclone.conf    
        - name: {{ include "qbittorrentvpn.fullname" . }}-rclone-cache
          persistentVolumeClaim:
            claimName: {{ include "qbittorrentvpn.fullname" . }}-rclone-cache                                                           
      initContainers:           
        - name: qbittorrent-scripts-config
          image: "busybox"
          command:
            - cp
          args:
            - -v
            - /in/liveness.sh
            - /out/liveness.sh
          volumeMounts:
          - name: health-data
            mountPath: /in
          - name: health
            mountPath: /out  
        - name: create-wireguard-config
          image: "busybox"
          command:
            - mkdir
          args:
            - -p
            - /out/wireguard
          volumeMounts:
          - name: {{ include "qbittorrentvpn.fullname" . }}-config-volume
            mountPath: /out                  
        - name: import-wireguard-config-for-qbittorrent
          image: "busybox"
          command:
            - cp
          args:
            - -v
            - /in/wg0.conf
            - /out/wireguard/wg0.conf
          volumeMounts:
          - name: wireguard-data-airvpn
            mountPath: /in
          - name: {{ include "qbittorrentvpn.fullname" . }}-config-volume
            mountPath: /out                
        - name: permission-fix-for-health
          image: busybox
          command: ['sh', '-c']
          args: ['chmod -R 777 /out']
          volumeMounts:
          - name: health
            mountPath: /out  
        - name: rclone-config
          image: "busybox"
          command:
            - cp
          args:
            - -v
            - /in/rclone.conf
            - /out/rclone.conf
          volumeMounts:
            - name: rclone-config
              mountPath: /in
            - name: rclone-data
              mountPath: /out
        - name: import-wireguard-config
          image: "busybox"
          command:
            - cp
          args:
            - -v
            - /in/wg2.conf
            - /out/wg2.conf
          volumeMounts:
            - name: wireguard-config
              mountPath: /in
            - name: wireguard-data
              mountPath: /out   
        - name: import-wireguard-config-2
          image: "busybox"
          command:
            - cp
          args:
            - -v
            - /in/wg-airvpn.conf
            - /out/wg-airvpn.conf
          volumeMounts:
            - name: wireguard-config-2
              mountPath: /in
            - name: wireguard-data
              mountPath: /out                                                                          
      containers:
        - image: luiscajl/rclone-wireguard
          name: rclone-wireguard
          imagePullPolicy: Always
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
            limits:
              cpu: "1000m"
              memory: "1000M"  
          command:
            [
              "sh",
              "-c",
              "wg-quick up wg2 && wg-quick up wg-airvpn && rclone mount --config=/etc/rclone/rclone.conf rclone-with-cache: /data --log-level=INFO --umask 002 --allow-other --allow-non-empty  --dir-cache-time 100h --cache-dir=/tmp/rclone-cache --vfs-cache-mode full --vfs-cache-max-size 350G --vfs-cache-max-age 24h --drive-stop-on-upload-limit --drive-stop-on-download-limit --tpslimit 8 --drive-upload-cutoff 1000T  --bind=10.10.10.2  ",
            ]
          volumeMounts:
            - mountPath: /data
              name: data
              mountPropagation: Bidirectional
            - mountPath: /etc/wireguard
              name: wireguard-data
            - mountPath: /etc/rclone
              name: rclone-data     
            - mountPath: /tmp/rclone-cache
              name: {{ include "qbittorrentvpn.fullname" . }}-rclone-cache       
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
           {{- range .Values.environmentVariables }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }} 
          volumeMounts:
            - mountPath: /config
              name: {{ include "qbittorrentvpn.fullname" . }}-config-volume  
            - mountPath: /scripts
              name: scripts                 
            - mountPath: /data
              name: data
              mountPropagation: Bidirectional
            - mountPath: /etc/localtime
              name: etc-localtime   
            - mountPath: /health
              name: health                  
          livenessProbe:
            exec:
              command:
                - bin/bash
                - -c
                - /health/liveness.sh
            initialDelaySeconds: 30
            timeoutSeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3                 
          readinessProbe:
            exec:
              command:
                - bin/bash
                - -c
                - /health/liveness.sh
            initialDelaySeconds: 30
            timeoutSeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3                        
          ports:
            - name: privoxy
              containerPort: 8181
              protocol: TCP
            - name: bittorrent-ui
              containerPort: {{ .Values.service.port }}
              protocol: TCP     
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "qbittorrentvpn.fullname" . }}-config-volume  
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi