spring:
  profile: ""
replicaCount: 1

image:
  repository: lavandadelpatio/filebot-executor
  pullPolicy: Always
  tag: "0.0.1-SNAPSHOT"


nfs:
  server: nfs.lavandadelpatio.es
  paths:
   media: /mnt/rclone-writer ## OUTPUT
   torrents: /mnt/rclone-writer/Torrenting ## INPUT  
filebot:
  pathInput: /media-input
  pathOutput: /media-output
  pathData: /home/filebot
  testEnabled: false
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: example.com 
      paths: [ /feed-films ]
  tls: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
